SET FOREIGN_KEY_CHECKS = 0;
drop table czlonkowie;
DROP table sekcje;
Drop table czlonkowie_w_sekcjach;
Drop table spotkania;
Drop table eventy;
drop table turnieje;
drop table sponsorowanie;
drop table placowki;
drop table miejsca;
drop table sponsorzy;
drop table uczestnicy_turniejow;
drop table miejsce_w_turnieju;
drop table egzemplarz;
drop table gry;
drop table gry_komputerowe;
drop table gry_planszowe;
drop table gry_uzywanie;
drop table platformy;
drop table wydawcy;
SET FOREIGN_KEY_CHECKS = 1;