INSERT into Sekcje(nazwa,data_utworzenia) values ('Gry strategiczne',CURRENT_DATE);
INSERT into Sekcje(nazwa,data_utworzenia) values ('Gry karciane',CURRENT_DATE);
INSERT into Czlonkowie(pesel,imie,nazwisko,data_urodzenia) values('00111450469','Maria','Nowak','2000-11-14');
INSERT into Czlonkowie(pesel,imie,nazwisko,data_urodzenia) values('03072876315','Jan','Kowalski','2003-07-28');
INSERT into Czlonkowie(pesel,imie,nazwisko,data_urodzenia) values('04022912378','Janusz','Lewandowski','2004-02-29');
INSERT into Czlonkowie(pesel,imie,nazwisko,data_urodzenia) values('01010177711','Mikolaj','Malinowski','2001-01-01');
INSERT into Czlonkowie_w_sekcjach values ('00111450469', 2, current_date());
INSERT into Czlonkowie_w_sekcjach values ('04022912378', 2, current_date());
INSERT into Czlonkowie_w_sekcjach values ('01010177711', 2, current_date());
INSERT into Czlonkowie_w_sekcjach values ('01010177711', 1, current_date());
INSERT into Czlonkowie_w_sekcjach values ('03072876315', 1, current_date());
INSERT into Placowki values('Polna 46',700);
INSERT into Placowki values('Wiejska 80',400);
INSERT INTO Spotkania(termin,id_sekcji,adres) values('2022-01-19',1,'Polna 46');
INSERT INTO Spotkania(termin,id_sekcji,adres) values('2022-01-25',2,'Polna 46');
INSERT INTO Spotkania(termin,id_sekcji,adres) values('2021-12-17',1,'Wiejska 80');
INSERT into Miejsca values('Polna 46',700,50);
INSERT into Miejsca values('Głowna 17',2000,500);
insert into Eventy(nazwa,data,sekcja,adres) values ('Kokon 2077','2077-02-15',2,'Polna 46');
insert into Eventy(nazwa,data,sekcja,adres) values ('Event strategow','2023-07-16',1,'Głowna 17');
insert into Sponsorzy(nazwa) values ('Miasto poznan');
insert into Sponsorzy(nazwa) values ('MDK');
insert into Sponsorowanie(kwota,sponsor,event) values (500,1,1);
insert into Sponsorowanie(kwota,sponsor,event) values (700,1,2);
insert into Sponsorowanie(kwota,sponsor,event) values (100,1,1);
insert into Sponsorowanie(kwota,sponsor,event) values (2,2,1);
insert into Sponsorowanie(kwota,sponsor,event) values (5,2,2);
insert into Turnieje(nazwa,event,godzina_rozpoczecia) values ('Keyforgers',1,'15:00');
insert into Turnieje(nazwa,event,godzina_rozpoczecia) values ('Kosiarze',2,'13:00');
insert into Uczestnicy_turniejow(imie,nazwisko,turniej) values ('Piotr','Malecki',1);
insert into Uczestnicy_turniejow(imie,nazwisko,turniej) values ('Sebastian','Lewandowski',1);
insert into Uczestnicy_turniejow(imie,nazwisko,turniej) values ('Jan','Piotrowski',2);
insert into Uczestnicy_turniejow(imie,nazwisko,turniej) values ('Krzysztof','Terlecki',2);
insert into Uczestnicy_turniejow(imie,nazwisko,turniej) values ('Maja','Kasznia',2);
insert into Miejsce_w_turnieju values (1,1,2,'50 zl');
insert into Miejsce_w_turnieju values (1,2,5,'100 zl');
Insert into Wydawcy(nazwa) values ('Rebel');
Insert into Wydawcy(nazwa) values ('Nasza Ksiegarnia');
Insert into Wydawcy(nazwa) values ('Ubisoft');
insert into Platformy(nazwa) values ('Uplay');
insert into Platformy(nazwa) values ('Steam');
insert into Gry(nazwa,cena,wydawca) values ('Smoki',50,2);
insert into Gry(nazwa,cena,wydawca) values ('Kruki',50,2);
insert into Gry(nazwa,cena,wydawca) values ('Scythe',150,1);
insert into Gry(nazwa,cena,wydawca) values ('Keyforge',70,1);
insert into Gry(nazwa,cena,wydawca) values ('Assasin Creed',100,3);
insert into Gry(nazwa,cena,wydawca) values ('Rainbow Siegie',60,3);
insert into Egzemplarz(id_gry,id_sekcji) values (1,2);
insert into Egzemplarz(id_gry,id_sekcji) values (1,2);
insert into Egzemplarz(id_gry,id_sekcji) values (2,2);
insert into Egzemplarz(id_gry,id_sekcji) values (3,1);
insert into Egzemplarz(id_gry,id_sekcji) values (3,1);
insert into Egzemplarz(id_gry,id_sekcji) values (3,1);
insert into Egzemplarz(id_gry,id_sekcji) values (4,2);
insert into Egzemplarz(id_gry,id_sekcji) values (5,1);
insert into Egzemplarz(id_gry,id_sekcji) values (6,1);
insert into Gry_komputerowe values (5,1);
insert into Gry_komputerowe values (5,2);
insert into Gry_komputerowe values (6,1);
insert into Gry_planszowe values (1,0.3,2,5);
insert into Gry_planszowe values (2,0.4,2,2);
insert into Gry_planszowe values (3,3.1,1,5);
insert into Gry_planszowe values (4,0.6,2,2);
insert into Gry_uzywanie values(4,2);
insert into Gry_uzywanie values(6,2);
insert into Gry_uzywanie values(7,1);