# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UIs/MainT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PopUps import *
from tables import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 619)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sekcje = QtWidgets.QWidget()
        self.tab_sekcje.setObjectName("tab_sekcje")

        self.pushButton_sekcje_dodaj = QtWidgets.QPushButton(self.tab_sekcje)
        self.pushButton_sekcje_dodaj.setGeometry(QtCore.QRect(30, 20, 111, 23))
        self.pushButton_sekcje_dodaj.setObjectName("pushButton_sekcje_dodaj")
        self.pushButton_sekcje_edytuj = QtWidgets.QPushButton(self.tab_sekcje)
        self.pushButton_sekcje_edytuj.setGeometry(QtCore.QRect(250, 20, 101, 23))
        self.pushButton_sekcje_edytuj.setObjectName("pushButton_sekcje_edytuj")
        self.pushButton_sekcje_usun = QtWidgets.QPushButton(self.tab_sekcje)
        self.pushButton_sekcje_usun.setGeometry(QtCore.QRect(150, 20, 91, 23))
        self.pushButton_sekcje_usun.setObjectName("pushButton_sekcje_usun")
        self.tabWidget.addTab(self.tab_sekcje, "")
        self.tab_czlonkowie = QtWidgets.QWidget()
        self.tab_czlonkowie.setObjectName("tab_czlonkowie")

        self.pushButton_czlonkowie_dodaj = QtWidgets.QPushButton(self.tab_czlonkowie)
        self.pushButton_czlonkowie_dodaj.setGeometry(QtCore.QRect(30, 20, 91, 23))
        self.pushButton_czlonkowie_dodaj.setObjectName("pushButton_czlonkowie_dodaj")
        self.pushButton_czlonkowie_usun = QtWidgets.QPushButton(self.tab_czlonkowie)
        self.pushButton_czlonkowie_usun.setGeometry(QtCore.QRect(130, 20, 91, 23))
        self.pushButton_czlonkowie_usun.setObjectName("pushButton_czlonkowie_usun")
        self.pushButton_czlonkowie_przypisz = QtWidgets.QPushButton(self.tab_czlonkowie)
        self.pushButton_czlonkowie_przypisz.setGeometry(QtCore.QRect(230, 20, 111, 23))
        self.pushButton_czlonkowie_przypisz.setObjectName("pushButton_czlonkowie_przypisz")
        self.label = QtWidgets.QLabel(self.tab_czlonkowie)
        self.label.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_czlonkowie, "")
        self.tab_spotkania = QtWidgets.QWidget()
        self.tab_spotkania.setObjectName("tab_spotkania")

        self.pushButton_spotkania_dodaj = QtWidgets.QPushButton(self.tab_spotkania)
        self.pushButton_spotkania_dodaj.setGeometry(QtCore.QRect(30, 20, 91, 23))
        self.pushButton_spotkania_dodaj.setObjectName("pushButton_spotkania_dodaj")
        self.pushButton_spotkania_usun = QtWidgets.QPushButton(self.tab_spotkania)
        self.pushButton_spotkania_usun.setGeometry(QtCore.QRect(130, 20, 101, 23))
        self.pushButton_spotkania_usun.setObjectName("pushButton_spotkania_usun")
        self.label_2 = QtWidgets.QLabel(self.tab_spotkania)
        self.label_2.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_spotkania, "")
        self.tab_placowki = QtWidgets.QWidget()
        self.tab_placowki.setObjectName("tab_placowki")

        self.pushButton_placowki_dodaj = QtWidgets.QPushButton(self.tab_placowki)
        self.pushButton_placowki_dodaj.setGeometry(QtCore.QRect(30, 20, 91, 23))
        self.pushButton_placowki_dodaj.setObjectName("pushButton_placowki_dodaj")
        self.pushButton_placowki_usun = QtWidgets.QPushButton(self.tab_placowki)
        self.pushButton_placowki_usun.setGeometry(QtCore.QRect(130, 20, 91, 23))
        self.pushButton_placowki_usun.setObjectName("pushButton_placowki_usun")
        self.pushButton_placowki_edytuj = QtWidgets.QPushButton(self.tab_placowki)
        self.pushButton_placowki_edytuj.setGeometry(QtCore.QRect(230, 20, 101, 23))
        self.pushButton_placowki_edytuj.setObjectName("pushButton_placowki_edytuj")
        self.tabWidget.addTab(self.tab_placowki, "")
        self.tab_egzemplarze_gier = QtWidgets.QWidget()
        self.tab_egzemplarze_gier.setObjectName("tab_egzemplarze_gier")

        self.pushButton_egzemplarze_gier_dodaj = QtWidgets.QPushButton(self.tab_egzemplarze_gier)
        self.pushButton_egzemplarze_gier_dodaj.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.pushButton_egzemplarze_gier_dodaj.setObjectName("pushButton_egzemplarze_gier_dodaj")
        self.pushButton_egzemplarze_gier_usun = QtWidgets.QPushButton(self.tab_egzemplarze_gier)
        self.pushButton_egzemplarze_gier_usun.setGeometry(QtCore.QRect(140, 20, 101, 23))
        self.pushButton_egzemplarze_gier_usun.setObjectName("pushButton_egzemplarze_gier_usun")
        self.tabWidget.addTab(self.tab_egzemplarze_gier, "")
        self.tab_gry_komputerowe = QtWidgets.QWidget()
        self.tab_gry_komputerowe.setObjectName("tab_gry_komputerowe")

        self.pushButton_gry_komputerowe_dodaj = QtWidgets.QPushButton(self.tab_gry_komputerowe)
        self.pushButton_gry_komputerowe_dodaj.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pushButton_gry_komputerowe_dodaj.setObjectName("pushButton_gry_komputerowe_dodaj")
        self.pushButton_gry_komputerowe_usun = QtWidgets.QPushButton(self.tab_gry_komputerowe)
        self.pushButton_gry_komputerowe_usun.setGeometry(QtCore.QRect(110, 20, 75, 23))
        self.pushButton_gry_komputerowe_usun.setObjectName("pushButton_gry_komputerowe_usun")
        self.tabWidget.addTab(self.tab_gry_komputerowe, "")
        self.tab_gry_planszowe = QtWidgets.QWidget()
        self.tab_gry_planszowe.setObjectName("tab_gry_planszowe")

        self.pushButton_gry_planszowe_dodaj = QtWidgets.QPushButton(self.tab_gry_planszowe)
        self.pushButton_gry_planszowe_dodaj.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pushButton_gry_planszowe_dodaj.setObjectName("pushButton_gry_planszowe_dodaj")
        self.pushButton_gry_planszowe_usun = QtWidgets.QPushButton(self.tab_gry_planszowe)
        self.pushButton_gry_planszowe_usun.setGeometry(QtCore.QRect(110, 20, 75, 23))
        self.pushButton_gry_planszowe_usun.setObjectName("pushButton_gry_planszowe_usun")
        self.tabWidget.addTab(self.tab_gry_planszowe, "")
        self.tab_platformy = QtWidgets.QWidget()
        self.tab_platformy.setObjectName("tab_platformy")

        self.pushButton_platformy_dodaj = QtWidgets.QPushButton(self.tab_platformy)
        self.pushButton_platformy_dodaj.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.pushButton_platformy_dodaj.setObjectName("pushButton_platformy_dodaj")
        self.pushButton_platformy_edytuj = QtWidgets.QPushButton(self.tab_platformy)
        self.pushButton_platformy_edytuj.setGeometry(QtCore.QRect(140, 20, 101, 23))
        self.pushButton_platformy_edytuj.setObjectName("pushButton_platformy_edytuj")
        self.tabWidget.addTab(self.tab_platformy, "")
        self.tab_wydawcy = QtWidgets.QWidget()
        self.tab_wydawcy.setObjectName("tab_wydawcy")

        self.pushButton_wydawcy_dodaj = QtWidgets.QPushButton(self.tab_wydawcy)
        self.pushButton_wydawcy_dodaj.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.pushButton_wydawcy_dodaj.setObjectName("pushButton_wydawcy_dodaj")
        self.pushButton_wydawcy_edytuj = QtWidgets.QPushButton(self.tab_wydawcy)
        self.pushButton_wydawcy_edytuj.setGeometry(QtCore.QRect(140, 20, 101, 23))
        self.pushButton_wydawcy_edytuj.setObjectName("pushButton_wydawcy_edytuj")
        self.tabWidget.addTab(self.tab_wydawcy, "")
        self.tab_eventy = QtWidgets.QWidget()
        self.tab_eventy.setObjectName("tab_eventy")

        self.pushButton_eventy_dodaj = QtWidgets.QPushButton(self.tab_eventy)
        self.pushButton_eventy_dodaj.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pushButton_eventy_dodaj.setObjectName("pushButton_eventy_dodaj")
        self.pushButton_eventy_usun = QtWidgets.QPushButton(self.tab_eventy)
        self.pushButton_eventy_usun.setGeometry(QtCore.QRect(110, 20, 75, 23))
        self.pushButton_eventy_usun.setObjectName("pushButton_eventy_usun")
        self.pushButton_eventy_edytuj = QtWidgets.QPushButton(self.tab_eventy)
        self.pushButton_eventy_edytuj.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.pushButton_eventy_edytuj.setObjectName("pushButton_eventy_edytuj")
        self.label_3 = QtWidgets.QLabel(self.tab_eventy)
        self.label_3.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_eventy, "")
        self.tab_miejsce_na_event = QtWidgets.QWidget()
        self.tab_miejsce_na_event.setObjectName("tab_miejsce_na_event")

        self.pushButton_miejsce_na_event_dodaj = QtWidgets.QPushButton(self.tab_miejsce_na_event)
        self.pushButton_miejsce_na_event_dodaj.setGeometry(QtCore.QRect(30, 20, 91, 23))
        self.pushButton_miejsce_na_event_dodaj.setObjectName("pushButton_miejsce_na_event_dodaj")
        self.pushButton_miejsce_na_event_edytuj = QtWidgets.QPushButton(self.tab_miejsce_na_event)
        self.pushButton_miejsce_na_event_edytuj.setGeometry(QtCore.QRect(130, 20, 101, 23))
        self.pushButton_miejsce_na_event_edytuj.setObjectName("pushButton_miejsce_na_event_edytuj")
        self.tabWidget.addTab(self.tab_miejsce_na_event, "")
        self.tab_sponsorzy = QtWidgets.QWidget()
        self.tab_sponsorzy.setObjectName("tab_sponsorzy")
        self.tableWidget_sponsorzy = QtWidgets.QTableWidget(self.tab_sponsorzy)
        self.tableWidget_sponsorzy.setGeometry(QtCore.QRect(10, 60, 781, 461))

        self.pushButton_sponsorzy_dodaj = QtWidgets.QPushButton(self.tab_sponsorzy)
        self.pushButton_sponsorzy_dodaj.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.pushButton_sponsorzy_dodaj.setObjectName("pushButton_sponsorzy_dodaj")
        self.pushButton_sponsorzy_dodaj_sponsoring = QtWidgets.QPushButton(self.tab_sponsorzy)
        self.pushButton_sponsorzy_dodaj_sponsoring.setGeometry(QtCore.QRect(140, 20, 101, 23))
        self.pushButton_sponsorzy_dodaj_sponsoring.setObjectName("pushButton_sponsorzy_dodaj_sponsoring")
        self.label_4 = QtWidgets.QLabel(self.tab_sponsorzy)
        self.label_4.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_sponsorzy, "")
        self.tab_turnieje = QtWidgets.QWidget()
        self.tab_turnieje.setObjectName("tab_turnieje")

        self.pushButton_turnieje_dodaj = QtWidgets.QPushButton(self.tab_turnieje)
        self.pushButton_turnieje_dodaj.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.pushButton_turnieje_dodaj.setObjectName("pushButton_turnieje_dodaj")
        self.pushButton_turnieje_usun = QtWidgets.QPushButton(self.tab_turnieje)
        self.pushButton_turnieje_usun.setGeometry(QtCore.QRect(140, 20, 91, 23))
        self.pushButton_turnieje_usun.setObjectName("pushButton_turnieje_usun")
        self.label_5 = QtWidgets.QLabel(self.tab_turnieje)
        self.label_5.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_turnieje_dodaj_gre = QtWidgets.QPushButton(self.tab_turnieje)
        self.pushButton_turnieje_dodaj_gre.setGeometry(QtCore.QRect(240, 20, 91, 23))
        self.pushButton_turnieje_dodaj_gre.setObjectName("pushButton_turnieje_dodaj_gre")
        self.pushButton_turnieje_usun_gre = QtWidgets.QPushButton(self.tab_turnieje)
        self.pushButton_turnieje_usun_gre.setGeometry(QtCore.QRect(340, 20, 91, 23))
        self.pushButton_turnieje_usun_gre.setObjectName("pushButton_turnieje_usun_gre")
        self.tabWidget.addTab(self.tab_turnieje, "")
        self.tab_uczestnicy_turniejow = QtWidgets.QWidget()
        self.tab_uczestnicy_turniejow.setObjectName("tab_uczestnicy_turniejow")

        self.pushButton_uczestnicy_turniejow_dodaj = QtWidgets.QPushButton(self.tab_uczestnicy_turniejow)
        self.pushButton_uczestnicy_turniejow_dodaj.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.pushButton_uczestnicy_turniejow_dodaj.setObjectName("pushButton_uczestnicy_turniejow_dodaj")
        self.pushButton_uczestnicy_turniejow_usun = QtWidgets.QPushButton(self.tab_uczestnicy_turniejow)
        self.pushButton_uczestnicy_turniejow_usun.setGeometry(QtCore.QRect(140, 20, 101, 23))
        self.pushButton_uczestnicy_turniejow_usun.setObjectName("pushButton_uczestnicy_turniejow_usun")
        self.label_6 = QtWidgets.QLabel(self.tab_uczestnicy_turniejow)
        self.label_6.setGeometry(QtCore.QRect(390, 20, 41, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_uczestnicy_turniejow)
        self.label_7.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_uczestnicy_turniejow, "")
        self.tab_miejsca_w_turniejach = QtWidgets.QWidget()
        self.tab_miejsca_w_turniejach.setObjectName("tab_miejsca_w_turniejach")

        self.label_8 = QtWidgets.QLabel(self.tab_miejsca_w_turniejach)
        self.label_8.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_miejsca_w_turniejach)
        self.label_9.setGeometry(QtCore.QRect(390, 20, 41, 21))
        self.label_9.setObjectName("label_9")
        self.pushButton_miejsca_w_turniejach_dodaj = QtWidgets.QPushButton(self.tab_miejsca_w_turniejach)
        self.pushButton_miejsca_w_turniejach_dodaj.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.pushButton_miejsca_w_turniejach_dodaj.setObjectName("pushButton_miejsca_w_turniejach_dodaj")
        self.pushButton_miejsca_w_turniejach_usun = QtWidgets.QPushButton(self.tab_miejsca_w_turniejach)
        self.pushButton_miejsca_w_turniejach_usun.setGeometry(QtCore.QRect(140, 20, 101, 23))
        self.pushButton_miejsca_w_turniejach_usun.setObjectName("pushButton_miejsca_w_turniejach_usun")
        self.tabWidget.addTab(self.tab_miejsca_w_turniejach, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.setupUi_my(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_sekcje_dodaj.setText(_translate("MainWindow", "Dodaj sekcje"))
        self.pushButton_sekcje_edytuj.setText(_translate("MainWindow", "Edytuj Sekcje"))
        self.pushButton_sekcje_usun.setText(_translate("MainWindow", "Usuń sekcje"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sekcje), _translate("MainWindow", "Sekcje"))
        self.pushButton_czlonkowie_dodaj.setText(_translate("MainWindow", "Dodaj członka"))
        self.pushButton_czlonkowie_usun.setText(_translate("MainWindow", "Usuń Członka"))
        self.pushButton_czlonkowie_przypisz.setText(_translate("MainWindow", "Przypisz do Sekcji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_czlonkowie), _translate("MainWindow", "Członkowie"))

        self.pushButton_spotkania_dodaj.setText(_translate("MainWindow", "Dodaj Spotkanie"))
        self.pushButton_spotkania_usun.setText(_translate("MainWindow", "Usuń Spotkanie"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spotkania), _translate("MainWindow", "Spotkania"))

        self.pushButton_placowki_dodaj.setText(_translate("MainWindow", "Dodaj Miejsce"))
        self.pushButton_placowki_usun.setText(_translate("MainWindow", "Usuń Miejsce"))
        self.pushButton_placowki_edytuj.setText(_translate("MainWindow", "Edytuj Miejsce"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_placowki), _translate("MainWindow", "Placówki"))

        self.pushButton_egzemplarze_gier_dodaj.setText(_translate("MainWindow", "Dodaj Egzemplarz"))
        self.pushButton_egzemplarze_gier_usun.setText(_translate("MainWindow", "Usuń Egzemplarz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_egzemplarze_gier), _translate("MainWindow", "Egzemplarze gier"))

        self.pushButton_gry_komputerowe_dodaj.setText(_translate("MainWindow", "Dodaj grę"))
        self.pushButton_gry_komputerowe_usun.setText(_translate("MainWindow", "Usuń grę "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gry_komputerowe), _translate("MainWindow", "Gry komputerowe"))

        self.pushButton_gry_planszowe_dodaj.setText(_translate("MainWindow", "Dodaj grę"))
        self.pushButton_gry_planszowe_usun.setText(_translate("MainWindow", "Usuń grę "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gry_planszowe), _translate("MainWindow", "Gry planszowe"))

        self.pushButton_platformy_dodaj.setText(_translate("MainWindow", "Dodaj Platformę"))
        self.pushButton_platformy_edytuj.setText(_translate("MainWindow", "Edytuj Platformę"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_platformy), _translate("MainWindow", "Platformy"))

        self.pushButton_wydawcy_dodaj.setText(_translate("MainWindow", "Dodaj Wydawce"))
        self.pushButton_wydawcy_edytuj.setText(_translate("MainWindow", "Edytuj Wydawce"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wydawcy), _translate("MainWindow", "Wydawcy"))

        self.pushButton_eventy_dodaj.setText(_translate("MainWindow", "Dodaj Event"))
        self.pushButton_eventy_usun.setText(_translate("MainWindow", "Usuń Event"))
        self.pushButton_eventy_edytuj.setText(_translate("MainWindow", "Edytuj Event"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_eventy), _translate("MainWindow", "Eventy"))

        self.pushButton_miejsce_na_event_dodaj.setText(_translate("MainWindow", "Dodaj Miejsce"))
        self.pushButton_miejsce_na_event_edytuj.setText(_translate("MainWindow", "Edytuj Miejsce"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_miejsce_na_event), _translate("MainWindow", "Miejsce na Event"))

        self.pushButton_sponsorzy_dodaj.setText(_translate("MainWindow", "Dodaj Sponsora"))
        self.pushButton_sponsorzy_dodaj_sponsoring.setText(_translate("MainWindow", "Dodaj Sponsoring"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sponsorzy), _translate("MainWindow", "Sponsorzy"))

        self.pushButton_turnieje_dodaj.setText(_translate("MainWindow", "Dodaj turniej"))
        self.pushButton_turnieje_usun.setText(_translate("MainWindow", "Usuń turniej"))
        self.pushButton_turnieje_dodaj_gre.setText(_translate("MainWindow", "Dodaj gre"))
        self.pushButton_turnieje_usun_gre.setText(_translate("MainWindow", "Usun gre"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_turnieje), _translate("MainWindow", "Turnieje"))

        self.pushButton_uczestnicy_turniejow_dodaj.setText(_translate("MainWindow", "Dodaj uczestnika"))
        self.pushButton_uczestnicy_turniejow_usun.setText(_translate("MainWindow", "Usuń uczestnika"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_uczestnicy_turniejow), _translate("MainWindow", "Uczestnicy Turniejów"))

        self.pushButton_miejsca_w_turniejach_dodaj.setText(_translate("MainWindow", "Dodaj wygranego"))
        self.pushButton_miejsca_w_turniejach_usun.setText(_translate("MainWindow", "Usuń wygranego"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_miejsca_w_turniejach), _translate("MainWindow", "Miejsca w Turniejach"))


    def setupUi_my(self,MainWindow):
        self.setup_buttons()
        # setup tabs
        self.tabs_objects = [self.tab_sekcje, self.tab_czlonkowie, self.tab_spotkania, self.tab_placowki, self.tab_egzemplarze_gier, self.tab_gry_komputerowe, self.tab_gry_planszowe, self.tab_platformy, self.tab_wydawcy, self.tab_eventy, self.tab_miejsce_na_event, self.tab_sponsorzy, self.tab_turnieje, self.tab_uczestnicy_turniejow, self.tab_miejsca_w_turniejach]

        self.tabWidget.currentChanged.connect(self.on_tab_change)


    def addConnection(self, connection):
        self.connection = connection
        self.on_tab_change(0)


    def setup_buttons(self):
        self.pushButton_sekcje_dodaj.clicked.connect(self.button_sekcje_dodaj_fun)
        self.pushButton_sekcje_usun.clicked.connect(self.button_sekcje_usun_fun)
        self.pushButton_sekcje_edytuj.clicked.connect(self.button_sekcje_edytuj_fun)
        self.pushButton_czlonkowie_dodaj.clicked.connect(self.button_czlonkowie_dodaj_fun)
        self.pushButton_czlonkowie_usun.clicked.connect(self.button_czlonkowie_usun_fun)
        self.pushButton_czlonkowie_przypisz.clicked.connect(self.button_czlonkowie_przypisz_fun)
        self.pushButton_spotkania_dodaj.clicked.connect(self.button_spotkania_dodaj_fun)
        self.pushButton_spotkania_usun.clicked.connect(self.button_spotkania_usun_fun)
        self.pushButton_placowki_dodaj.clicked.connect(self.button_placowki_dodaj_fun)
        self.pushButton_placowki_usun.clicked.connect(self.button_placowki_usun_fun)
        self.pushButton_placowki_edytuj.clicked.connect(self.button_placowki_edytuj_fun)
        self.pushButton_egzemplarze_gier_dodaj.clicked.connect(self.button_egzemplarze_gier_dodaj_fun)
        self.pushButton_egzemplarze_gier_usun.clicked.connect(self.button_egzemplarze_gier_usun_fun)
        self.pushButton_gry_komputerowe_dodaj.clicked.connect(self.button_gry_komputerowe_dodaj_fun)
        self.pushButton_gry_komputerowe_usun.clicked.connect(self.button_gry_komputerowe_usun_fun)
        self.pushButton_gry_planszowe_dodaj.clicked.connect(self.button_gry_planszowe_dodaj_fun)
        self.pushButton_gry_planszowe_usun.clicked.connect(self.button_gry_planszowe_usun_fun)
        self.pushButton_platformy_dodaj.clicked.connect(self.button_platformy_dodaj_fun)
        # self.pushButton_platformy_usun.clicked.connect(self.button_platformy_usun_fun)
        self.pushButton_platformy_edytuj.clicked.connect(self.button_platformy_edytuj_fun)
        self.pushButton_wydawcy_dodaj.clicked.connect(self.button_wydawcy_dodaj_fun)
        # self.pushButton_wydawcy_usun.clicked.connect(self.button_wydawcy_usun_fun)
        self.pushButton_wydawcy_edytuj.clicked.connect(self.button_wydawcy_edytuj_fun)
        self.pushButton_eventy_dodaj.clicked.connect(self.button_eventy_dodaj_fun)
        self.pushButton_eventy_usun.clicked.connect(self.button_eventy_usun_fun)
        self.pushButton_eventy_edytuj.clicked.connect(self.button_eventy_edytuj_fun)
        self.pushButton_miejsce_na_event_dodaj.clicked.connect(self.button_miejsce_dodaj_fun)
        self.pushButton_miejsce_na_event_edytuj.clicked.connect(self.button_miejsce_edytuj_fun)
        self.pushButton_sponsorzy_dodaj.clicked.connect(self.button_sponsorzy_dodaj_fun)
        self.pushButton_sponsorzy_dodaj_sponsoring.clicked.connect(self.button_sponsorzy_dodaj_sponsoring_fun)
        self.pushButton_turnieje_dodaj.clicked.connect(self.button_turnieje_dodaj_fun)
        self.pushButton_turnieje_usun.clicked.connect(self.button_turnieje_usun_fun)
        self.pushButton_uczestnicy_turniejow_dodaj.clicked.connect(self.button_uczestnicy_turniejow_dodaj_fun)
        self.pushButton_uczestnicy_turniejow_usun.clicked.connect(self.button_uczestnicy_turniejow_usun_fun)
        self.pushButton_miejsca_w_turniejach_dodaj.clicked.connect(self.button_miejsca_w_turniejach_dodaj_fun)
        self.pushButton_miejsca_w_turniejach_usun.clicked.connect(self.button_miejsca_w_turniejach_usun_fun)
        self.pushButton_turnieje_dodaj_gre.clicked.connect(self.button_gra_turniej_dodaj_fun)
        self.pushButton_turnieje_usun_gre.clicked.connect(self.button_gra_turniej_usun_fun)

    def button_base(self, ui, tab: int):
        self.ChangedObject = QtWidgets.QDialog()
        ui.setupUi(self.ChangedObject, self.connection)
        self.ChangedObject.exec_()
        #self.ChangedObject.show()
        self.on_tab_change(tab)


    def button_sekcje_dodaj_fun(self):
        ui = Ui_CreateSekcja()
        self.button_base(ui, 0)

    def button_czlonkowie_dodaj_fun(self):
        ui = Ui_AddCzlonek()
        self.button_base(ui, 1)

    def button_spotkania_dodaj_fun(self):
        ui = Ui_AddSpotkanie()
        self.button_base(ui, 2)

    def button_placowki_dodaj_fun(self):
        ui = Ui_AddPlacowka()
        self.button_base(ui, 3)

    def button_egzemplarze_gier_dodaj_fun(self):
        ui = Ui_AddEgzemplarz()
        self.button_base(ui, 4)

    def button_gry_komputerowe_dodaj_fun(self):
        ui = Ui_AddGraKomputerowa()
        self.button_base(ui, 5)

    def button_gry_planszowe_dodaj_fun(self):
        ui = Ui_AddGraPlanszowa()
        self.button_base(ui, 6)

    def button_platformy_dodaj_fun(self):
        ui = Ui_AddPlatforma()
        self.button_base(ui, 7)

    def button_wydawcy_dodaj_fun(self):
        ui = Ui_AddWydawca()
        self.button_base(ui, 8)

    def button_eventy_dodaj_fun(self):
        ui = Ui_AddEvent()
        self.button_base(ui, 9)

    def button_miejsce_dodaj_fun(self):
        ui = Ui_AddMiejsce()
        self.button_base(ui, 10)

    def button_sponsorzy_dodaj_fun(self):
        ui = Ui_AddSponsor()
        self.button_base(ui, 11)

    def button_turnieje_dodaj_fun(self):
        ui = Ui_AddTurniej()
        self.button_base(ui, 12)

    def button_uczestnicy_turniejow_dodaj_fun(self):
        ui = Ui_AddUczestnik()
        self.button_base(ui, 13)

    def button_miejsca_w_turniejach_dodaj_fun(self):
        ui = Ui_AddWygrany()
        self.button_base(ui, 14)


    def button_sekcje_usun_fun(self):
        self.DeleteSekcja = QtWidgets.QDialog()
        ui = Ui_DeleteWithLineEdit()
        ui.setupUi(self.DeleteSekcja, 0, "sekcję", "nazwa", self.connection)
        self.DeleteSekcja.exec_()
        self.on_tab_change(0)

    def button_czlonkowie_usun_fun(self):
        self.DeleteCzlonek = QtWidgets.QDialog()
        ui = Ui_DeleteWithLineEdit()
        ui.setupUi(self.DeleteCzlonek, 1, "członka", "PESEL", self.connection)
        self.DeleteCzlonek.exec_()
        self.on_tab_change(1)

    def button_placowki_usun_fun(self):
        self.DeletePlacowka = QtWidgets.QDialog()
        ui = Ui_DeleteWithLineEdit()
        ui.setupUi(self.DeletePlacowka, 3, "miejsce spotkań", "Adres", self.connection)
        self.DeletePlacowka.exec_()
        self.on_tab_change(3)

    def button_egzemplarze_gier_usun_fun(self):
        self.DeleteEgzemplarz = QtWidgets.QDialog()
        ui = Ui_DeleteWithLineEdit()
        ui.setupUi(self.DeleteEgzemplarz, 4, "egzemplarz gry", "id_egzemplarza", self.connection)
        self.DeleteEgzemplarz.exec_()
        self.on_tab_change(4)

    def button_eventy_usun_fun(self):
        self.DeleteEvent = QtWidgets.QDialog()
        ui = Ui_DeleteWithLineEdit()
        ui.setupUi(self.DeleteEvent, 9, "event", "nazwa", self.connection)
        self.DeleteEvent.exec_()
        self.on_tab_change(9)

    def button_uczestnicy_turniejow_usun_fun(self):
        self.DeleteUczestnik = QtWidgets.QDialog()
        ui = Ui_DeleteWithLineEdit()
        ui.setupUi(self.DeleteUczestnik, 13, "uczestnika", "id_uczestnika", self.connection)
        self.DeleteUczestnik.exec_()
        self.on_tab_change(13)

    def button_miejsca_w_turniejach_usun_fun(self):
        self.DeleteWygrany = QtWidgets.QDialog()
        ui = Ui_DeleteWithLineEdit()
        ui.setupUi(self.DeleteWygrany, 14, "miejsce w turnieju", "ID uczestnika", self.connection)
        self.DeleteWygrany.show()
        self.on_tab_change(14)

    def button_spotkania_usun_fun(self):
        ui = Ui_DeleteSpotkanie()
        self.button_base(ui, 2)

    def button_gry_komputerowe_usun_fun(self):
        ui = Ui_DeleteGraKomputerowa()
        self.button_base(ui, 5)

    def button_gry_planszowe_usun_fun(self):
        ui = Ui_DeleteGraPlanszowa()
        self.button_base(ui, 6)

    def button_turnieje_usun_fun(self):
        ui = Ui_DeleteTurniej()
        self.button_base(ui, 12)


    def button_sekcje_edytuj_fun(self):
        self.ChangedObject = QtWidgets.QDialog()
        ui = Ui_UpdateNameName()
        ui.setupUi(self.ChangedObject, 0, "sekcji", self.connection)
        self.ChangedObject.exec_()
        self.ChangedObject.show()
        self.on_tab_change(0)

    def button_platformy_edytuj_fun(self):
        self.ChangedObject = QtWidgets.QDialog()
        ui = Ui_UpdateNameName()
        ui.setupUi(self.ChangedObject, 7, "platformy", self.connection)
        self.ChangedObject.exec_()
        self.ChangedObject.show()
        self.on_tab_change(7)

    def button_wydawcy_edytuj_fun(self):
        self.ChangedObject = QtWidgets.QDialog()
        ui = Ui_UpdateNameName()
        ui.setupUi(self.ChangedObject, 8, "wydawcy", self.connection)
        self.ChangedObject.exec_()
        self.ChangedObject.show()
        self.on_tab_change(8)

    def button_miejsce_edytuj_fun(self):
        self.UpdateMiejsceCena = QtWidgets.QDialog()
        ui = Ui_UpdateAdrCost()
        ui.setupUi(self.UpdateMiejsceCena, 10, "cenę wynajmu", "cena_wynajmu", self.connection)
        self.UpdateMiejsceCena.exec_()
        self.UpdateMiejsceCena.show()
        self.on_tab_change(10)

    def button_placowki_edytuj_fun(self):
        self.UpdatePlacowka = QtWidgets.QDialog()
        ui = Ui_UpdateAdrCost()
        ui.setupUi(self.UpdatePlacowka, 3, "czynsz placówki", "czynsz", self.connection)
        self.UpdatePlacowka.exec_()
        self.UpdatePlacowka.show()
        self.on_tab_change(3)


    def button_sponsorzy_dodaj_sponsoring_fun(self):
        ui = Ui_AddSponsoring()
        self.button_base(ui, 11)

# -------------------------------

    def button_gra_turniej_dodaj_fun(self):
        ui = Ui_AddGraTurniej()
        self.button_base(ui, 12)

    def button_czlonkowie_przypisz_fun(self):
        ui = Ui_AssignCzlonekSekcja()
        self.button_base(ui, 1)


    def button_eventy_edytuj_fun(self):
        ui = Ui_UpdateEventSekcja()
        self.button_base(ui, 9)

    def button_gra_turniej_usun_fun(self):
        ui = Ui_DeleteGraTurniej()
        self.button_base(ui, 12)



    def on_tab_change(self, tab_nr):
        table, headers = get_table(tab_nr, self.connection)
        self.show_table(tab_nr, table, headers)

    def show_table(self, tab, table: list, headers: list):
        # table - list of rows

        width = len(table[0])
        heigth = len(table)

        self.tableWidget_new = QtWidgets.QTableWidget(self.tabs_objects[tab])
        self.tableWidget_new.setGeometry(QtCore.QRect(10, 60, 771, 461))
        self.tableWidget_new.setObjectName("tableWidget_new")
        self.tableWidget_new.setColumnCount(width)
        self.tableWidget_new.setRowCount(heigth)

        self.tableWidget_new.setSortingEnabled(True)
        _translate = QtCore.QCoreApplication.translate

        # headers
        for i in range(heigth):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_new.setVerticalHeaderItem(i, item)
            item = self.tableWidget_new.verticalHeaderItem(i)
            item.setText(_translate("MainWindow", str(i)))


        for i in range(width):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_new.setHorizontalHeaderItem(i, item)
            item = self.tableWidget_new.horizontalHeaderItem(i)
            item.setText(_translate("MainWindow", headers[i]))

        # data
        for i, row in enumerate(table):
            for j, value in enumerate(row):
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget_new.setItem(i,j, item)
                item = self.tableWidget_new.item(i, j)
                item.setText(_translate("MainWindow", value))

        self.tableWidget_new.setSortingEnabled(True)
        self.tableWidget_new.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_new.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
